name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (sanity check)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Deploy using publish profile only - the repository secret must be named 
      # 'AZURE_WEBAPP_PUBLISH_PROFILE' and contain the full XML from Azure portal's publish profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
